packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  "sass": "^1.70.0"
  "solid-devtools": "^0.29.2"
  "typescript": "^5.3.3"
  "vite": "^5.0.11"
  "vite-plugin-solid": "^2.8.2"
  "solid-js": "^1.8.11"