packages:
    - 'apps/*'
    - 'libs/*'

catalog:
    '@storybook/addon-essentials': '8.0.5'
    '@storybook/addon-interactions': '8.0.5'
    '@storybook/addon-links': '8.0.5'
    '@storybook/blocks': '8.0.5'
    '@storybook/html': '8.0.5'
    'sass': '^1.70.0'
    'solid-devtools': '^0.29.2'
    'solid-js': '^1.8.11'
    'storybook': '^8.2.4'
    'storybook-solidjs': '^1.0.0-beta.2'
    'storybook-solidjs-vite': '^1.0.0-beta.2'
    'typescript': '^5.3.3'
    'vite': '^5.0.11'
    'vite-plugin-solid': '^2.8.2'
