export enum FacilityTypeEnum {
    STORAGE = 'STORAGE',
    PRODUCTION = 'PRODUCTION',
}

// METAL_MINE = 'METAL_MINE',
//     CRYSTAL_MINE = 'CRYSTAL_MINE',
//     DEUTERIUM_SYNTHESIZER = 'DEUTERIUM_SYNTHESIZER',
//     SOLAR_POWER_PLANT = 'SOLAR_POWER_PLANT',
//     FUSION_POWER_PLANT = 'FUSION_POWER_PLANT',
//     METAL_SHED = 'METAL_SHED',
//     CRYSTAL_SHED = 'CRYSTAL_SHED',
//     DEUTERIUM_SHED = 'DEUTERIUM_SHED',
