name: CI

on:
    pull_request:
        branches:
            - 'main'
            - 'releases/**'
            - 'develop'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    actions: write
    contents: read

jobs:
    changed-files:
        runs-on: ubuntu-latest
        name: Test changed-files
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get changed files in the ui lib folder
              id: changed-files-yaml
              uses: tj-actions/changed-files@v44
              with:
                  files_yaml: |
                      neogame_web:
                        - apps/neogame-web/**
                      ui:
                        - libs/ui/**

            - name: Log changed files in apps/neogame-web
              if: ${{ steps.changed-files-yaml.outputs.neogame_web_any_changed == 'true' || steps.changed-files-yaml.outputs.ui_any_changed == 'true' }}
              env:
                  NEOGAME_WEB_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.neogame_web_all_changed_files }}
              run: |
                  echo "One or more file(s) in the neogame-web application has changed."
                  echo "$NEOGAME_WEB_ALL_CHANGED_FILES" | tr ' ' '\n'

            - name: Log changed files in libs/ui
              if: steps.changed-files-yaml.outputs.ui_any_changed == 'true'
              env:
                  UI_ALL_CHANGED_FILES: ${{ steps.changed-files-yaml.outputs.ui_all_changed_files }}
              run: |
                  echo "One or more file(s) in the ui library has changed."
                  echo "$UI_ALL_CHANGED_FILES" | tr ' ' '\n'

    logweb:
        runs-on: ubuntu-latest
        needs: [changed-files]
        steps:
            - name: log value
              run: |
                  echo ${{ needs.changed-files-yaml.outputs.neogame-web_any_changed }}
                  echo ${{ needs.changed-files-yaml.outputs.ui_any_changed }}

    neogame-web:
        name: Run Neogame-CI
        needs: [changed-files]
        if: ${{ needs.changed-files-yaml.outputs.neogame-web_any_changed == 'true' || needs.changed-files-yaml.outputs.ui_any_changed == 'true' }}
        uses: ./.github/workflows/neogame-web-ci.yml
        secrets: inherit
#    chromatic:
#        name: Run visual tests
#        needs: [changed-files]
#        if: needs.changed-files-yaml.outputs.ui_any_changed == 'true'
#        uses: ./.github/workflows/chromatic.yml
#        secrets: inherit
