name: Continuous Integration

on:
    pull_request:
        branches:
            - 'main'
            - 'releases/**'
            - 'develop'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    actions: write
    contents: read

jobs:
    detect-affected:
        runs-on: ubuntu-latest
        name: Detect affected apps and libraries
        outputs:
            neogame_web_affected: ${{ steps.scan.outputs.neogame_web_any_changed == 'true' || steps.scan.outputs.ui_any_changed == 'true' }}
            ui_affected: ${{ steps.scan.outputs.ui_any_changed == 'true' }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Detect apps and libraries with code changes
              id: scan
              uses: tj-actions/changed-files@v44
              with:
                  files_yaml: |
                      neogame_web:
                        - apps/neogame-web/**
                      ui:
                        - libs/ui/**

    neogame-web:
        name: apps/neogame-web
        needs: [detect-affected]
        if: ${{ needs.detect-affected.outputs.neogame_web_affected }}
        uses: ./.github/workflows/neogame-web.yml
        secrets: inherit

    ui:
        name: libs/ui
        needs: [detect-affected]
        if: ${{ needs.detect-affected.outputs.ui_affected }}
        uses: ./.github/workflows/ui.yml
        secrets: inherit
