name: Neogame-Web CI

on: workflow_call

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-chromatic
    cancel-in-progress: true

permissions:
    actions: write
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        name: Test changed-files
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: pnpm/action-setup@latest
              name: Install pnpm
              with:
                  run_install: false

            - uses: actions/setup-node@latest
              with:
                  node-version-file: 'package.json'
                  cache: pnpm
                  registry-url: https://registry.npmjs.org

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build application
              run: pnpm --filter @oogo/neogame build
